### ISSUE TITLE
Quick Sample Image Service broken

### ISSUE THREAD

**Issue by jglorian** [chbrandt/dachs-doc#12]
SRCURL=http://dc.g-vo.org/emi/q/s/siap.xml
curl -s $SRCURL"?POS=163.3,57.8&SIZE=20,20&MAXREC=5&weighting=uniform" \
  | tr '<TD>' '\n' \
  | grep "^http://" \
  | sed -e 's/<[^>]*>//g' \
  | xargs -n1 curl -sO

does not work because the data of the votable is binary, need to convert the votable in ascii votable to coninue ...

**Comment by msdemlei** [comment]
On Thu, Feb 18, 2021 at 07:14:19AM -0800, jglorian wrote:
> SRCURL=http://dc.g-vo.org/emi/q/s/siap.xml
> curl -s $SRCURL"?POS=163.3,57.8&SIZE=20,20&MAXREC=5&weighting=uniform" \
>   | tr '<TD>' '\n' \
>   | grep "^http://" \
>   | sed -e 's/<[^>]*>//g' \
>   | xargs -n1 curl -sO
> 
> does not work because the data of the votable is binary, need to
> convert the votable in ascii votable to coninue ... 

Oh, ouch, I've removed that hack that forced the default to tabledata
in SIAP a while ago.

Well, DALI to the rescue: Just append a &RESPONSEFORMAT=votabletd to
the URI.

I've added that to the command line in the tutorial in commit f6c237c.
