### ISSUE TITLE
Regressions tests don’t pass in the Quick Sample SSAP Service

### ISSUE THREAD

**Issue by jglorian** [chbrandt/dachs-doc#13]
According to the tutorial
I have downloaded all the files for que Quick Sample SSAP service
> /var/gavo/inputs/zcosmos# tree.
> ├── README
> ├── bin
> │   ├── fixunit.py
> │   └── makepreviews.py
> ├── data
> │   └── zCOSMOS_BRIGHT_DR2_000826802_ZCMRa26_M1_Q4_13_1.fits
> ├── previews
> └── q.rd

when i try ti generate the preview to pass the regression tests  I have 
> /var/gavo/inputs/zcosmos# python3 bin/makepreviews.py
> 0 files processed, 0 files with errors

and when I try to rerun the tests regression I have still
> /var/gavo/inputs/zcosmos# dachs test q
> EEEE
> 4 of 4 bad.  avg 0.04, min 0.01, max 0.11. 37.8/s, par 1.6
> From zcosmos/q:
> 	FAIL zcosmos datalink generation
> 	FAIL zCOSMOS preview
> 	FAIL zCOSMOS SSA interface works
> 	ERROR zcosmos obscore

**Comment by jglorian** [comment]
in fact first I see a mistake in q.rd the path of the data is wrong

> <data id = "import">
> .................
> <sources pattern>"data/1D/zCOMSOS_BRIGHT_DR2_*.fits"/> 
 to replace with  
> <sources pattern>"data/zCOMSOS_BRIGHT_DR2_*.fits"/> 

but I still have the problem

> root@387c6d24e226:/var/gavo/inputs/zcosmos# dachs imp q
> Making data zcosmos/q#import
> Starting ...data/zCOSMOS_BRIGHT_DR2_000826802_ZCMRa26_M1_Q4_13_1.fits
> Done ...data/zCOSMOS_BRIGHT_DR2_000826802_ZCMRa26_M1_Q4_13_1.fits, read 1
> Shipped 1/1
> Create index raw_data_splitpos_raw_data
> Create index raw_data_accref
> Create index raw_data_ssa_location
> Create index raw_data_ssa_region
> Create index raw_data_obscore_data_did_index
> Rows affected: 1
> Making dependent zcosmos/q#make_view
> PythonScriptRunner executing script addTableToObscore on data
> PythonScriptRunner executing script createObscoreView on data
> root@387c6d24e226:/var/gavo/inputs/zcosmos# dachs test q
> EEE.
> 3 of 4 bad.  avg 0.04, min 0.01, max 0.10. 39.2/s, par 1.6
> From zcosmos/q:
> 	FAIL zCOSMOS preview
> 	FAIL zcosmos datalink generation
> 	FAIL zCOSMOS SSA interface works
> 
> 
> root@387c6d24e226:/var/gavo/inputs/zcosmos# python3 bin/makepreviews.py 
> 1 files processed, 0 files with errors
> root@387c6d24e226:/var/gavo/inputs/zcosmos# dachs test q
> EEE.
> 3 of 4 bad.  avg 0.05, min 0.01, max 0.14. 27.9/s, par 1.4
> From zcosmos/q:
> 	FAIL zcosmos datalink generation
> 	FAIL zCOSMOS preview
> 	FAIL zCOSMOS SSA interface works
>

**Comment by msdemlei** [comment]
On Thu, Feb 18, 2021 at 12:21:21PM -0800, jglorian wrote:
> and when I try to rerun the tests regression I have still
> > /var/gavo/inputs/zcosmos# dachs test q
> > EEEE
> > 4 of 4 bad.  avg 0.04, min 0.01, max 0.11. 37.8/s, par 1.6
> > From zcosmos/q:
> > 	FAIL zcosmos datalink generation
> > 	FAIL zCOSMOS preview
> > 	FAIL zCOSMOS SSA interface works
> > 	ERROR zcosmos obscore

The direct reason of this is that the pattern attribute of source
reflects what I'm doing in Heidelberg, and I clearly hadn't thought
about that when coming up with this example.  But it's worse: Now
that I've looked a bit closer it turns out that this isn't a good
SSAP example at all.

Unfortunately, non-painful spectral collection is close to an
oxymoron -- I chose this because it required the least hacks, but
that's only because I didn't fix inheret problems of the dataset
itself.

Let me think a bit about how to do the SSA quick start.  I'll do
something about it next week.  Until then: Don't worry about this
failure and step boldly ahead.

And of course thanks for pointing me to this; accepting bad
documentation helps nobody.

**Comment by jglorian** [comment]
ok in fact to work,  I have to,
move data/zCOSMOS_BRIGHT_DR2_000826802_ZCMRa26_M1_Q4_13_1.fits in  
data/1D/zCOSMOS_BRIGHT_DR2_000826802_ZCMRa26_M1_Q4_13_1.fits

and also to change the tests

> diff q.rd  qorigin.rd 
> 245c245
> < 					PUBDID="ivo://jglorian/~?zcosmos/data/1D/zCOSMOS_BRIGHT_DR2_000826802_ZCMRa26_M1_Q4_13_1.fits"
> ---
> > 					PUBDID="ivo://org.gavo.dc/~?zcosmos/data/1D/zCOSMOS_BRIGHT_DR2_000826802_ZCMRa26_M1_Q4_13_1.fits"
> 262c262,263
> < 				self.assertHasStrings("PNG")			</code>
> ---
> > 				self.assertHasStrings("PNG", "g$|B")
> > 			</code>
> 267c268
> < 				ID="ivo://jglorian/~?zcosmos/data/1D/zCOSMOS_BRIGHT_DR2_000826802_ZCMRa26_M1_Q4_13_1.fits"
> ---
> > 				ID="ivo://org.gavo.dc/~?zcosmos/data/1D/zCOSMOS_BRIGHT_DR2_000826802_ZCMRa26_M1_Q4_13_1.fits"
> 
> 
it would be good to explain that in the tutorial

**Comment by msdemlei** [comment]
As said in the comment to commit 4762f4b, it's been a bad idea to use zcosmos for this in the first place.  I'm now using a different data collection in the tutorial.

Thanks again for reporting this.
