### ISSUE TITLE
data sources for templates

### ISSUE THREAD

**Issue by ygrange** [chbrandt/dachs-doc#8]
Heya,

When I wanted to edit the default root.html template to include author information, I got a bit lost in trying to find how to access that data. You have a pretty decent explanation of the nevow framework in the docs, and a list of renderes but I think it would also be nice to have an idea of the data sources for n:data tags. I would assume there are a few functions whose main purpose is to gather data to be used here and I would think it being a good idea to have them listed, including the structure of the returned data.

**Comment by msdemlei** [comment]
I'm closing the issue after the section header in templating.rstx is changed.  I'm sure there's more that needs improvement to make this clearer, but that's for another day.

As to allowing arbitarary services as root pages: that'd be a DaCHS wishlist item.  I'm putting it on my private list.  If you'd use that, let me know and I'll give it a bit more priority.
